### ISSUE TITLE
 encryption part

### ISSUE THREAD

**Issue by Mike-3** [SparkDustJoe/RabbitManaged#1]
Do you happen to have a piece of code for the encryption and decryption?

**Comment by SparkDustJoe** [comment]
All the example code for use is in the test program. Note: this isn't optimized code and is several years old, so it could benefit from the advancements of .Net 6 or being further optimized in C++/CLR.  While all tests pass from the RFC, this is also for informational purposes only, and shouldn't be used for production without a security audit, either for this source as it is or for the final version built into whatever project you have.

**Comment by Mike-3** [comment]
Thanks for the hint.  But I don't want to use the code in a critical application.  I also ported it to Dart.  Unfortunately there is no UInt32.  But the tests are now running.  It should only be used in a geocaching app. 
Thanks for your code.
